import Head from "next/head";
import { About } from "../sections/About";
import { Banner } from "../sections/Banner";
import { Contacts } from "../sections/Contacts";
import { Footer } from "../sections/Footer";
import { Formations } from "../sections/Formations";
import { Header } from "../sections/Header";
import { Projects } from "../sections/Projects";
import { Skills } from "../sections/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Protifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <Banner />
        <About />
        <Skills />
        <Formations />
        <Projects />
        {/* <Contacts /> */}
        <Footer />
      </div>
    </>
  );
}
